### PR TITLE
Update jupyterhub to version 3.0.0

### PR DESCRIPTION
**Pull request by danyel2014**
python-jupyterhub v1.4.1 -> v3.0.0

### CODE REVIEW

**Comment by PromyLOPh** [comment]
How do you run it? It fails with this error for me:

```
[E 2022-09-14 06:52:37.140 JupyterHub proxy:762] Failed to find proxy ['configurable-http-proxy']
    The proxy can be installed with `npm install -g configurable-http-proxy`.To install `npm`, install nodejs which includes `npm`.If you see an `EACCES` error or permissions error, refer to the `npm` documentation on How To Prevent Permissions Errors.
[C 2022-09-14 06:52:37.140 JupyterHub app:3054] Failed to start proxy
    Traceback (most recent call last):
      File "/gnu/store/51xf4w18yi2yyx3p9imqhfbp055sh2jl-python-jupyterhub-3.0.0/lib/python3.9/site-packages/jupyterhub/app.py", line 3052, in start
        await self.proxy.start()
      File "/gnu/store/51xf4w18yi2yyx3p9imqhfbp055sh2jl-python-jupyterhub-3.0.0/lib/python3.9/site-packages/jupyterhub/proxy.py", line 758, in start
        self.proxy_process = Popen(
      File "/gnu/store/qar3sks5fwzm91bl3d3ngyrvxs7ipj5z-python-3.9.9/lib/python3.9/subprocess.py", line 951, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/gnu/store/qar3sks5fwzm91bl3d3ngyrvxs7ipj5z-python-3.9.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'configurable-http-proxy'
```

**Comment by danyel2014** [comment]
Hi, 
I've cloned the galaxy-science repo, made the changes in `guix-science/packages/jupyter.scm`, set `GUIX_PACKAGE_PATH` to my clone path and the run `guix build python-jupyterhub`.

I got a similar error like you when I've tried to build by using only the `guix import` output without disabling the tests ( without `(arguments `(#:tests? #f))`).

After disabling the tests, adjusted the name of `python-tornado -> python-tornado-6` and added the missing dep `python-notebook`, it built with success.
Dan

**Comment by PromyLOPh** [comment]
I’m sorry, I mean how do you run jupyterhub in your environment. I applied your patch and it builds, but when trying to run it via `guix shell --no-cwd -L . python-jupyterhub python-notebook --pure -C -- jupyterhub` it spits out the error above. The current version does the same though, so I’m wondering how people use this package. Do you manually install the requested configurable-http-proxy?

**Comment by danyel2014** [comment]
indeed, I install configurable-http-proxy manually and run the jupyterhub as a systemd service which sets NODE_PATH=/path/to/node_modules .

It would be nice to have configurable-http-proxy packed and installed automatically as a dependency, but that's over my power.

I've asked @rekado about a nodejs importer, but so far there is nothing available.

**Comment by PromyLOPh** [comment]
I added configurable-http-proxy and it seems to work with

```
guix shell -L . python-jupyterhub python-notebook --no-cwd -C -N --share=/tmp -- jupyterhub --config=/tmp/config.py --debug
```

config.py:
```python
c = get_config()  # noqa

from jupyterhub.auth import DummyAuthenticator
c.JupyterHub.authenticator_class = DummyAuthenticator

from jupyterhub.spawner import SimpleLocalProcessSpawner
c.JupyterHub.spawner_class = SimpleLocalProcessSpawner
```

Can you give it a try?

**Comment by danyel2014** [comment]
how can I reproduce "I added configurable-http-proxy" ?  already  tried` guix pull`, I don't see the package

**Comment by danyel2014** [comment]
closed the PR by mistake, sry

**Comment by danyel2014** [comment]
I figure out myself where are your changes (+ configurable-http-proxy) and I confirm, it works. I'll create a new PR

**Pull request closed without merging**
