### PR TITLE
rstudio desktop is crashing when File Chooser Dialog is called

### PR DESCRIPTION
**Pull request by pimi17**
Fix the crash of the RStudio GUI when the File Chooser Dialog was used, by setting the GSETTINGS_SCHEMA_DIR.

### CODE REVIEW

**Comment by PromyLOPh** [comment]
I cannot reproduce this issue on a foreign distribution inside a `guix environment --pure` and selecting File→Open File. Can you give some details how to reproduce the issue and which environment is used?

**Comment by pimi17** [comment]
Hi, sorry that I did not describe the problem!

We run Guix on Ubuntu 18. 
We encountered this when we run RStudio Desktop and we used the option of saving/open a file.

`Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'`

With strace I found this

```
24982 openat(AT_FDCWD, "/usr/share/glib-2.0/schemas/gschemas.compiled", O_RDONLY <unfinished ...>
25046 <... read resumed> "\1\0\0\0\2\0\0\0\0\0\0\0\20\0\0\0log\0\0\0\0\0\0\0\0\0\0\0\0\0", 180000) = 32
24982 <... openat resumed> )            = 89
```


I am not sure if my solution is the best, but after I tested the newly built RStudio with my patch in the same environment I got rid of the problem.

Let me know if you need more details!

**Comment by PromyLOPh** [comment]
That file is never opened in my environment. Are you by any chance using a GTK-backed QT theme? If so, could you try without?

**Comment by pimi17** [comment]
Many of the intern users complain about this bug and from what I checked now, they use the Ambiance theme.

I tested now with multiple themes, I got the same result.

```
~$ gsettings get org.gnome.desktop.interface gtk-theme
'Adwaita'
~$ rstudio
/gnu/store/pwcp239kjf7lnj5i4lkdzcfcxwcfyk72-bash-minimal-5.0.16/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

(process:30979): Gtk-WARNING **: 17:41:24.701: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 17:41:24.787: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:41:24.788: Failed to load module "canberra-gtk-module"

(rstudio:30979): GLib-GIO-ERROR **: 17:41:41.644: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
```


```
~$ gsettings get org.gnome.desktop.interface gtk-theme
'Adwaita-dark'
~$ rstudio
/gnu/store/pwcp239kjf7lnj5i4lkdzcfcxwcfyk72-bash-minimal-5.0.16/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

(process:31287): Gtk-WARNING **: 17:42:44.311: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 17:42:44.370: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:42:44.370: Failed to load module "canberra-gtk-module"

(rstudio:31287): GLib-GIO-ERROR **: 17:42:55.005: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
```

Any ideas??

**Comment by rekado** [comment]
I can confirm that this issue exists in the wild, and that it's terribly difficult to reproduce.  The root cause here is always one of load order.  Usually we get lucky and the directories from Guix are picked up first.  But once in a while we will have a situation where on application start-up the wrong cache file is loaded (like this global file here), and the result is that GTK modules that are loaded later will come from the system environment.

We have a couple of these GSETTINGS_SCHEMA_DIR fixes in Guix itself.  Examples include pcsxr, darktable, wxmaxima, and utox.  I think this fix is appropriate.  The only question I have is why it isn't used in more packages.

I note that all affected packages use the cmake-build-system.  The glib-or-gtk-build-system avoids this problem by wrapping all executables, ensuring that the GTK directories from Guix are always consulted first.

**Comment by rekado** [comment]
@pimi17 Could you please sign your commit and update this pull request?

**Comment by PromyLOPh** [comment]
@pimi17 RStudio is a Qt application. It does not use GTK at all. Could you (privately, if you want) share an `strace` and the full `env` where this is running?

**Comment by rekado** [comment]
Closing due to inactivity and age (both mine and the age of this issue).

**Pull request closed without merging**
